version: "3.7"
services:
  web:
    image: nginx
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
      - ./html:/usr/share/nginx/html:ro
    restart: always
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
volumes:
  repacs_db:
    driver: local